---

extends:
  - airbnb
  - "plugin:jest/recommended"

parser: babel-eslint

plugins:
  - jest

env:
  browser: true
  jest:    true

rules:
  no-multi-spaces: 0
  key-spacing:     0
  react/jsx-props-no-spreading:
    - 2
    - custom: ignore